### ISSUE TITLE
Render paved tracks in different way than unpaved  

### ISSUE THREAD

**Issue by ray66** [hotosm/HDM-CartoCSS#173]
Currently the surface and tracktype of tracks is not taken into account, all tracks are rendered in the same way. I propose to differentiate paved/unpaved tracks depending on the surface attribute. The rendering style could be:

unpaved tracks: unchanged
paved track: as today, without the brown pattern, i.e.  like unclassified but with thinner border.

The current rendering of tracks is probably sufficient for most areas where HOT intervened in the past. In other regions there are a lot of highway=track, surface=paved|asphalt, for example in Germany and, for a lesser extent, in France. Now that the style has made its way into the OSM main page, and for being prepared for humanitary intervention in all regions of the world, it would be usefull to have this tracks rendrered differently from unpaved ones .

**Comment by matkoniecz** [comment]
> I wonder if a paved track is still a track?

Yes, as highway=track is defined by function (used for forestry/agriculture) rather than by quality. Some forests in Poland have high quality roads constructed/currently used mainly for forestry use (in addition used by tourists, primarily cyclists).

In 2008 it was [explicitly documented](http://wiki.openstreetmap.org/w/index.php?title=Template:Map_Features:highway&diff=110537&oldid=110431) that highway=track that "used for agriculture and forestry" is defining track, not its surface. It restored initial definition from 2006 [that was allowing paved roads implicitly](http://wiki.openstreetmap.org/w/index.php?title=Map_Features&diff=prev&oldid=8537) and reverted [change that in 2006 documented tracks as always unpaved](http://wiki.openstreetmap.org/w/index.php?title=Map_Features&diff=prev&oldid=14014).
