### ISSUE TITLE
Road links are extremely narrow on z12, leading to bad rendering of T shaped junctions.

### ISSUE THREAD

**Issue by matkoniecz** [hotosm/HDM-CartoCSS#236]
As result T shaped motorway junctions on z12 and z11 are weird. Note that at on other zoom levels everything looks OK.

http://www.openstreetmap.org/?mlat=50.0125&mlon=20.0566#map=12/50.0125/20.0566&layers=H

**Comment by skorasaurus** [comment]
This was fixed in the recent roads refactoring =) https://github.com/hotosm/HDM-CartoCSS/commit/8604d963becdc153efffe8cd1b27dedc00472661

I've tested it with a local extract of krakow for confirmation. 

To the left was the previous styling; to the right is the refactoring, as of https://github.com/hotosm/HDM-CartoCSS/commit/f26975c114fd46a0676e1cc7ef4264afb1088854 
![selection_026](https://cloud.githubusercontent.com/assets/955351/12011901/afe7a5d4-acaf-11e5-91a3-0994382c761b.png)

This updated, refactored version has been deployed to the server earlier this week but it may take some more days for lower zoom levels to display. 

Re-open if you find any other examples that were not fixed.
