### ISSUE TITLE
oneway=-1 rendered as if it was oneway=yes

### ISSUE THREAD

**Issue by kdano** [hotosm/HDM-CartoCSS#261]
Streets with the oneway=-1 tag are rendered the wrong way, as if the value was "yes".

**Comment by skorasaurus** [comment]
Confirmed.

The title of the issue is a little confusing, but I understand what you mean: 

An example of this is at: http://www.openstreetmap.org/#map=18/41.47908/-81.73872&layers=H

In the example, the road is supposed to be one way to the north (and I've been there months ago); but in our rendering, the arrows are drawn to point south. 

This is because the road drawn as (north to south) in OSM. The proper OSM usage would be to reverse the way and change the tag to oneway=yes. 

I'd prefer not to render oneway=-1 at all. It does not sound that as if there are many reasons for it to be used but it is still used quite a bit. 145,000 times - http://taginfo.openstreetmap.org/keys/?key=oneway#values

thoughts @yohanboniface

**Comment by yohanboniface** [comment]
Humm, I agree that reversing the way would be a more conventional way to tag, but I'm not sure we can stop rendering "-1": it's still used, as you mention, plus it's a [documented value](http://wiki.openstreetmap.org/wiki/Tag%3Aoneway%3D-1#List_of_values), which seems to mean that we are not in a deprecation situation.

So I would fix the code to properly support "-1" value instead of dropping it. :)

(BTW, Github issues are really a pain: this is another example of issue I totally missed. :( )

**Comment by kdano** [comment]
I totally agree with you guys (and sorry about the confusion).
I never tag oneway=-1, but I don't think there's a chance it will ever disappear. E.g. because map editors will always offer to use it when the users reverse way objects, and there will always be people reversing ways..
So I think it's better to fix the rendering

**Comment by kdano** [comment]
so how long does it take for this to go live? the above example is still rendered incorrectly @yohanboniface

**Comment by kdano** [comment]
and still
