### ISSUE TITLE
Render public marketplaces (amenity=market_place)

### ISSUE THREAD

**Issue by jeisenbe** [hotosm/HDM-CartoCSS#304]
Market places, also known as Public markets, Farmer's Markets, Bazaars, Mercados (Spanish), Pasar (Indonesia/Malaysian/Malay), are the most important landmarks in traditional towns, especially in the non-Western world. Most towns in Southeast Asia, Africa and Latin American started around a marketplace, and these are often important landmarks and destinations. In many places vegetables are only sold at the marketplace, although greengrocers and supermarkets are becoming more common in cities.  

Currently amenity=market_place is not yet rendered in the HDM-CartoCSS style. I would recommend rendering with the same symbol used by the Openstreetmap-carto style, with initial zoom level based partial on the size of the area for closed ways, and at z16 for nodes. Alternately it could have the same Maki cart symbol as supermarkets, although it is unusual to use shopping trolleys or carts in public marketplaces. 

Current HDM-CartoCSS style for Pasar Potikelek in Wamena, Papua Indonesia:
![potikelek-hdm](https://user-images.githubusercontent.com/42757252/47400171-0a60db80-d777-11e8-8c5c-7fdf4dcf3476.png)

Current Openstreetmap-carto rendering, with market icon and name label: 
![potikelek-osmcarto](https://user-images.githubusercontent.com/42757252/47400172-0a60db80-d777-11e8-9193-99a1d5fc29bf.png)

(I would be happy to do some test renderings, once I figure out how to set up Kosmtik with the HDM-CartoCSS style. I already have set up Docker, on MacOS 10.13.16 to render Openstreetmap-carto style)

**Comment by skorasaurus** [comment]
Jeisenble, 

Thank you for reporting and offering to volunteer to help to do test renderings. The marketplace is certainly important and deserves an icon as you described. Unfortunately, I know both of us have been busy so we haven't contributed lately but we do accept pull requests and . 

Also, [amenity=marketplace](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmarketplace) is used much more often than [amenity=market_place.](https://taginfo.openstreetmap.org/tags/amenity=market_place) and to use the one without the _ going ahead. 

This is already an issue of this on https://github.com/hotosm/HDM-CartoCSS/issues/22 so I'll close this issue but as @jeisenbe described, that should also be modified so that we render it when it is an area or as a node.

**Comment by jeisenbe** [comment]
Oops, I tried searching the other issues, but I missed it, due to
misspelling marketplace as market_place! Sorry for the duplicate.

I’m in Indonesia and bandwidth is pricey, so I’d like to reuse the shape
files and docker containers from the openstreetmap-carto style.

Is there any documentation about rendering this style with docker and
kosmtik?


Joseph
